# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.45
  min_vel_x: 0.1

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.6

  acc_lim_x: 2.5
  acc_lim_theta: 3.2

# Goal Tolerance Parameters
  # Check: stay outside footprint
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.15
  latch_xy_goal_tolerance: false  # do not rotate on finding goal

# Forward Simulation Parameters
  # Check: minimum velocity multiplied by the sim_period is less than twice the tolerance on a goal. 
  sim_time: 1.0                   # The amount of time to forward-simulate trajectories in seconds
  sim_granularity: 0.1            # The step size, in meters, to take between points on a given trajectory
  angular_sim_granularity: 0.2    # The step size, in radians, to take between angular samples on a given trajectory.
  vx_samples: 6                   # The number of samples to use when exploring the x velocity space
  vtheta_samples: 20              # The number of samples to use when exploring the theta velocity space

# Trajectory Scoring Parameters
  meter_scoring: true             # If true, distances are expressed in meters; otherwise grid cells
  path_distance_bias: 0.6         # The weighting for how much the controller should stay close to the path it was given
  goal_distance_bias: 0.8         # The weighting for how much the controller should attempt to reach its local goal,controls speed
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 1
