obstacle_range: 1.0
raytrace_range: 1.5

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
# distance a circular robot should be clear of the obstacle
# if the robot is circular
# robot_radius: 0.2 
# if the robot is not circular
footprint: [[-0.10, 0.30], [0.33, 0.30], [0.33, -0.30], [-0.10, -0.30]]
# max. distance from an obstacle at which costs are incurred for
# planning paths.
inflation_radius: 0.38
# exponential rate at which the obstacle cost drops off (default: 10)
cost_scaling_factor: 5

map_type: costmap
observation_sources: scan
scan: {
  sensor_frame: lidar_link, 
  data_type: LaserScan, 
  topic: scan, 
  marking: true, 
  clearing: true
  }