footprint: [[-0.13, -0.23], [0.33, -0.23], [0.33, 0.23], [-0.13, 0.23]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5
rolling_window: true

resolution: 0.02

obstacle_range: 1.5
raytrace_range: 2.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.35

aggressive_reset:
  reset_distance: 1.0