local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 5
   publish_frequency: 0.5
   static_map: false
   rolling_window: true
   width: 1.5
   height: 1.5
   resolution: 0.05
   transform_tolerance: 0.5
