# .yaml config file
#
# The PID gains and controller settings must be saved in a yaml file that gets loaded
# to the param server via the roslaunch file (mirobot_control.launch).

mirobot:
  # Publish all joint states -----------------------------------
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------
  leftWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_0_joint
    #pid: {p: 10.0, i: 0.0, d: 0.0}
    pid: {p: 100, i: 0.1, d: 10.0}
  rightWheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_1_joint
    #pid: {p: 10.0, i: 0.0, d: 0.0}
    pid: {p: 100, i: 0.1, d: 10.0}
    