
obstacle_range: 2.5
raytrace_range: 3.5
footprint: [[-0.13, -0.23], [0.33, -0.23], [0.33, 0.23], [-0.13, 0.23]]
footprint_padding: 0.01
#robot_radius: 0.105
inflation_radius: 0.35
cost_scaling_factor: 0.5
map_type: costmap
transform_tolerance: 0.2
observation_sources: scan
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true}